# Generated by Django 4.2 on 2026-01-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_person_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='static/img/default_avatar.jpg', upload_to='media/avatars/', verbose_name='用户头像'),
        ),
    ]
