# Generated by Django 4.2 on 2026-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_person_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='static/img/default_avatar.jpg', upload_to='avatars/', verbose_name='用户头像'),
        ),
    ]
