# Generated by Django 4.2 on 2026-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_person_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='site_titlet',
        ),
        migrations.AddField(
            model_name='blog',
            name='site_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='站点标题'),
        ),
    ]
