# Generated by Django 4.2 on 2026-01-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_blog_site_titlet_blog_site_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='create_data',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
