# Generated by Django 4.2 on 2026-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_comments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_title',
            field=models.CharField(default='默认站点名称', max_length=20, verbose_name='站点标题'),
        ),
    ]
