# Generated by Django 4.2 on 2026-02-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_blog_site_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='app01.tags'),
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars/', verbose_name='用户头像'),
        ),
    ]
