# Generated by Django 4.2 on 2026-02-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_articles_tags_alter_person_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='app01.tags'),
        ),
    ]
