# Generated by Django 4.2 on 2026-06-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_articles_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '站点', 'verbose_name_plural': '站点'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='upordowns',
            options={'verbose_name': '点赞点踩', 'verbose_name_plural': '点赞点踩'},
        ),
    ]
